### ISSUE TITLE
M40A3 changes

### ISSUE THREAD

**Issue by pellerichard** [promod/promod4#7]
There is a rumor (which seems to be true) about the snipers, R700's ads speed is slightly faster than M40A3, could we make the M40A3's ads speed same as R700?

**Comment by sunspinx** [comment]
Isn't that done on purpose because R700 has 4 bullets and M4A03 5?

like there's need to be difference otherwise we can have only 1 scope

**Comment by pellerichard** [comment]
Indeed, but if you check current top scopes, you can see that the majority of them are using R700 because they know that having that 1 extra bullet will not be a round saver. If it was meant to be like this, then keep it like this, it's just really weird for me, as I don't see anyone using M40A3 nowadays when they know about the R700 ads speed feature.

**Comment by Ingramz** [comment]
I'm gonna reopen this until there is evidence which either supports or debunks the claim made in first post. Reviewing the code, there doesn't seem to be any differences between the two rifles when it comes to the time it takes to fully engage aiming down the sight with a loaded rifle..

**Comment by Ingramz** [comment]
I didn't find any differences between the two, even when measuring the number of frames it takes from ads click to reach to a steady scope.
